---
- name: creating a file with 774  permissions on all hosts 
  hosts: all 
  remote_user: root

  tasks: # creating a file with 774  permissions
    - name: creating a file 
      file: 
        path: /tmp/ansibletest1
        state: touch
        mode: "u=rwx,g=rwx,o=r" # or 0774        